export default[
    {value:"Antiprotozoals"},
    {value:"Antiinfective"}, 
    {value:"ARV_MEDICINES"},
    {value:"ANTIVIRALS"},
    {value:"BLOOD PRODUCTS AND MEDICINES AFFECTING THE BLOOD"},
    {value:"DISORDERS AND CONTRACCEPTIVES"},
    {value:"MEDICINES USED IN MUSCULO SKELETAL AND JOINT DISEASES"},
    {value:"RESPIRATORY MEDICINES"},
    {value:"CENTRAL NERVOUS SYSTEM MEDICINES"},
    {value:"OPHTHALMIC AGENTS"},
    {value:"EAR, NOSE AND THROAT PREPARATIONS"},
    {value:"ANTIDOTES AND OTHER SUBSTANCES"},
    {value:"DERMATOLOGICAL AGENTS"},
    {value:"ANTI CANCER MEDICINES AND ADJUVANTS"},
    {value:"GASTROINTESTINAL MEDICINES"},
    {value:"TNF inhibitor"},
    {value:"CARDIOVASCULAR MEDICINES"},
    {value:"LIST OF REGULAR MEDICAL SUPPLIES"},
    {value:"Antiseptic"},
    {value:"VITAMINS"},
    {value:"Urological and Related Medicines"},
    {value:"MEDICINES USED IN BPH"},
    {value:"Gastro intestinal medicine"},
    {value:"ANXIOLYTIC"},
    {value:"OBSTETRIC AND GYNAECOLOGICAL MEDICATIONS"},
    {value:"Dermatology"}, 
    {value:"MEDICINES FOR"}, 
    {value:"CAPITAL  MEDICAL EQUIPMENT"},
    {value:"CAPITAL  MEDICAL EQUIPMENT"},
    {value:"IMMUNOLOGICAL PREPARATIONS"},
    {value:"MALARIA PHARMACEUTICALS"},
    {value:"MALARIA PHARMACEUTICALS"},
    {value:"Anti-infective"},
    {value:"MEDICINES USED IN ANAESTHESIA"},
    {value:"TUBERCULOSIS DIAGNOSTICS & LABORATORY  REAGENTS"},
    {value:"Nucleic Acid Synthesis Inhibitors [MoA],Nucleoside Metabolic Inhibitor [EPC]"},
    {value:"Interleukin 2 Receptor Antagonists [MoA]"},
    {value:"VACCINES"},
    {value:"Retinoid [EPC],Retinoids [Chemical/Ingredient]"},
    {value:"Antinfective"},
    {value:"Antineoplastic"},
    {value:"Anihypertensive agent"},
    {value:"Muskuleskeletal agents"},
    {value:"Endocrine"},
    {value:"Stimulant"},
    {value:"Calcium regulator"},
    {value:"Anti diabetis"},
    {value:"TB MEDICAL SUPPLIES"},
    {value:"Antifungal Agent"},
    {value:"MEDICAL  IMAGING  SUPPLIES  AND  CHEMICALS"},
    {value:"CHEMICALS AND STAINS"},
    {value:"ANTI-SEPTICS"}, 
    {value:"Dietary supplement"},
    {value:"Antiplatelet Agent"},
    {value:"Calcimimetic"},
    {value:" Agent"},
    {value:"CLINICAL CHEMISTRY REAGENTS"},
    {value:"Antilipemic Agent, Bile Acid Sequestrant"},
    {value:"Contraceptive"},
    {value:"FAMILY PLANNING CONTRACEPTIVES"},
    {value:"Kidny transplant preservation solution"}, 
    {value:"Vitamines"}, 
    {value:"Low Molecular Weight Heparin"},
    {value:"HEMATOLOGY CLOSED  SYSTEM  REAGENTS"},
    {value:"GASTROESOPHAGEAL REFLUX"},
    {value:"NONSTEROIDAL ANTI INFILAMATORY DRUG"},
    {value:"ANTI INFECTION"}, 
    {value:"Anti-infective/Anthelmintic/Antifilariasis"},
    {value:"Radio-pharmaceuticals"},
    {value:"PEDIATRIC  ANTI-TUBERCULOSIS MEDICINES"},
    {value:"TBL PHARMACEUTICALS"},
    {value:"ANTI-FUNGAL"},
    {value:"ANTI-NEOPLASTIC AND ADJUVANTS"},
    {value:"Central Nurvious syetm"}, 
    {value:"MEDICINES USED IN ENDOCRINEDISORDERS AND CONTRACCEPTIVES"},
    {value:"Antidote, Hypoglycemia & Diagnostic Agent"},
    {value:"Steroidal Anti-inflammatory"},
    {value:"Vitamines and Minerals"}, 
    {value:"MEDICNE FOR FLUID-ELECTROLYTE IMBALANCE"}, 
    {value:"AGENT"},
    {value:"DERMATOLOGICAL AGENT"},
    {value:"RADIOGRAPHIC CONTRAST AGENT"},
    {value:"LABORATORY SUPPLIES"},
    {value:"DISORDERS"},
    {value:"Local/Topical Anesthetics"},
    {value:"DISORDERS"},
    {value:"Anti fungal"},
    {value:"GASTROINTESTINAL MEDICINE"},
    {value:"GASTROINTESTINAL /FLUID-ELECTROLYTE SUPPLEMENT"}, 
    {value:"GASTRO INTESTINAL ANTI-INFLAMATORY AGENT"},
    {value:"HEMORRHAGIC CYSTITIS INHIBITOR"},
    {value:"MEDICIN USED IN INDOCRINE/MALE SEX HORMONE PREPATATIONS AND ITS ANTAGONISTS"},
    {value:"DISORDERS /Hypoglycemic Agent"},
    {value:"ANTITHYROID DRUGS"},
    {value:"Oxytocic/ ergot alkaloids"},
    {value:"ANALGESIC, TOPICAL"},
    {value:"STEROIDAL ANTI-INFLAMATORY AGENTS"},
    {value:"INOTROPIC"},
    {value:"MATERNAL HEALTH MEDICINES"},
    {value:"ANTINEOPLASTIC"},
    {value:"VACCINE ACCESSORIES"},
    {value:"ANALEPTIC/ CNS stimulant"},
    {value:"ANTI-LEPROSY  MEDICINES"},
    {value:"ANTIHELMINTICS"},
    {value:"SMOKING DETERRENT"},
    {value:"ANTIPROTOZOALS"},
    {value:"ANTIDIARRHEAL"},
    {value:"Dermatological"}, 
    {value:"Anti-epileptic Agent"},
    {value:"Urinary Tract Anti-spasmodics"}, 
    {value:"Opioid Agonists"}, 
    {value:"ENDOCRINE-METABOLIC AGENT"},
    {value:"GRANULOCYTE COLONY STIMULATING FACTOR"},
    {value:"HEMORRHEOLOGIC AGENT (xanthine)"},
    {value:"[EPC],Decreased Central Nervous System Disorganized Electrical Activity [PE],Cytochrome P450 1A2 Inducers [MoA],Cytochrome P450 2B6 Inducers [MoA],Cytochrome P450 2C8 Inducers [MoA],Cytochrome P450 2C19 Inducers [MoA],Cytochrome P450 2D6 Inducers [MoA],Cytochrome P450 3A Inducers [MoA],Cytochrome P450 2C9 Inducers [MoA]"},
    {value:"Gastrointestinal"},
    {value:"Nutrition"},
    {value:"Urinary Alkalinizer"},
    {value:"Antihyperthyroid"},
    {value:"Electrolyte Supplement, Oral"},
    {value:"Antilipemic Agent, HMG-CoA Reductase Inhibitor"},
    {value:"Antihypertensive"},
    {value:"Neuropathic Pain Agent"},
    {value:"Antimalaria"},
    {value:"Testosterone replacement therapy"}, 
    {value:"Antidiarrheal"},
    {value:"Miscellaneous ocular agents"},
    {value:"ANTIHEMOPHILIC AGENT"}, 
    {value:"ELECTROLYTE REPLACEMENT THERAPY"}, 
    {value:"CALCIUM REGULATOR"}, 
    {value:"ANTICOAGULANT"},
    {value:"Neuromuscular Blocking Agent"},
    {value:"ANESTHETIC"}, 
    {value:"RESPIRATORY MEDICINE"}, 
    {value:"SEROLOGICAL AND IMMUNOASSAY"},
    {value:"ELECTROLYE MODIFIERS"},
    {value:"IMMUNOSUPPRESSENT"},
    {value:"MEDICINES USED IN ENDOCRINE"},
    {value:"CORRECTING WATER ELECTROLYTE AND ACID- BASE DISTURBANCES"},
    {value:"NASAL MOISTURIZATION"}, 
    {value:"MUSCULO SKELETAL "},
    {value:"ANTI MALARIAL"},
    {value:"ANTI INFECTIVES"},
    {value:"OPPORTUNISTIC INFECTION MEDICINES"},
    {value:"LOCAL ANESTESIA"},
    {value:"THERAPEUTIC FOOD SUPPLEMENT"},
    {value:"RESPARATORY MEDICINE"},
    {value:"BLOOD PRODUCTS & MEDICINES AFFECTING THE BLOOD"},
    {value:"ENDOCRINE DISORDERS MEDICINES"},
    {value:"ANTI VIRAL AGENT"}, 
    {value:"DEFICIENCY DEASES"},
    {value:"ANTI NEOPLASTIC AGENT"},
    {value:"TREATMENT OF HEADACHE"},









]