 export default[
    "Antiprotozoals",
    "Antiinfective", 
    "ARV_MEDICINES",
    "ANTIVIRALS",
    "BLOOD PRODUCTS AND MEDICINES AFFECTING THE BLOOD",
    "DISORDERS AND CONTRACCEPTIVES",
    "MEDICINES USED IN MUSCULO SKELETAL AND JOINT DISEASES",
    "RESPIRATORY MEDICINES",
    "CENTRAL NERVOUS SYSTEM MEDICINES",
    "OPHTHALMIC AGENTS",
    "EAR, NOSE AND THROAT PREPARATIONS",
    "ANTIDOTES AND OTHER SUBSTANCES",
    "DERMATOLOGICAL AGENTS",
    "ANTI CANCER MEDICINES AND ADJUVANTS",
    "GASTROINTESTINAL MEDICINES",
    "TNF inhibitor",
    "CARDIOVASCULAR MEDICINES",
    "LIST OF REGULAR MEDICAL SUPPLIES",
    "Antiseptic",
    "VITAMINS",
    "Urological and Related Medicines",
    "MEDICINES USED IN BPH",
    "Gastro intestinal medicine",
    "ANXIOLYTIC",
    "OBSTETRIC AND GYNAECOLOGICAL MEDICATIONS",
    "Dermatology", 
    "MEDICINES FOR", 
    "CAPITAL  MEDICAL EQUIPMENT",
    "CAPITAL  MEDICAL EQUIPMENT",
    "IMMUNOLOGICAL PREPARATIONS",
    "MALARIA PHARMACEUTICALS",
    "MALARIA PHARMACEUTICALS",
    "Anti-infective",
    "MEDICINES USED IN ANAESTHESIA",
    "TUBERCULOSIS DIAGNOSTICS & LABORATORY  REAGENTS",
    "Nucleic Acid Synthesis Inhibitors [MoA],Nucleoside Metabolic Inhibitor [EPC]",
    "Interleukin 2 Receptor Antagonists [MoA]",
    "VACCINES",
    "Retinoid [EPC],Retinoids [Chemical/Ingredient]",
    "Antinfective",
    "Antineoplastic",
    "Anihypertensive agent",
    "Muskuleskeletal agents",
    "Endocrine",
    "Stimulant",
    "Calcium regulator",
    "Anti diabetis",
    "TB MEDICAL SUPPLIES",
    "Antifungal Agent",
    "MEDICAL  IMAGING  SUPPLIES  AND  CHEMICALS",
    "CHEMICALS AND STAINS",
    "ANTI-SEPTICS", 
    "Dietary supplement",
    "Antiplatelet Agent",
    "Calcimimetic",
    " Agent",
    "CLINICAL CHEMISTRY REAGENTS",
    "Antilipemic Agent, Bile Acid Sequestrant",
    "Contraceptive",
    "FAMILY PLANNING CONTRACEPTIVES",
    "Kidny transplant preservation solution", 
    "Vitamines", 
    "Low Molecular Weight Heparin",
    "HEMATOLOGY CLOSED  SYSTEM  REAGENTS",
    "GASTROESOPHAGEAL REFLUX",
    "NONSTEROIDAL ANTI INFILAMATORY DRUG",
    "ANTI INFECTION", 
    "Anti-infective/Anthelmintic/Antifilariasis",
    "Radio-pharmaceuticals",
    "PEDIATRIC  ANTI-TUBERCULOSIS MEDICINES",
    "TBL PHARMACEUTICALS",
    "ANTI-FUNGAL",
    "ANTI-NEOPLASTIC AND ADJUVANTS",
    "Central Nurvious syetm", 
    "MEDICINES USED IN ENDOCRINEDISORDERS AND CONTRACCEPTIVES",
    "Antidote, Hypoglycemia & Diagnostic Agent",
    "Steroidal Anti-inflammatory",
    "Vitamines and Minerals", 
    "MEDICNE FOR FLUID-ELECTROLYTE IMBALANCE", 
    "AGENT",
    "DERMATOLOGICAL AGENT",
    "RADIOGRAPHIC CONTRAST AGENT",
    "LABORATORY SUPPLIES",
    "DISORDERS",
    "Local/Topical Anesthetics",
    "DISORDERS",
    "Anti fungal",
    "GASTROINTESTINAL MEDICINE",
    "GASTROINTESTINAL /FLUID-ELECTROLYTE SUPPLEMENT", 
    "GASTRO INTESTINAL ANTI-INFLAMATORY AGENT",
    "HEMORRHAGIC CYSTITIS INHIBITOR",
    "MEDICIN USED IN INDOCRINE/MALE SEX HORMONE PREPATATIONS AND ITS ANTAGONISTS",
    "DISORDERS /Hypoglycemic Agent",
    "ANTITHYROID DRUGS",
    "Oxytocic/ ergot alkaloids",
    "ANALGESIC, TOPICAL",
    "STEROIDAL ANTI-INFLAMATORY AGENTS",
    "INOTROPIC",
    "MATERNAL HEALTH MEDICINES",
    "ANTINEOPLASTIC",
    "VACCINE ACCESSORIES",
    "ANALEPTIC/ CNS stimulant",
    "ANTI-LEPROSY  MEDICINES",
    "ANTIHELMINTICS",
    "SMOKING DETERRENT",
    "ANTIPROTOZOALS",
    "ANTIDIARRHEAL",
    "Dermatological", 
    "Anti-epileptic Agent",
    "Urinary Tract Anti-spasmodics", 
    "Opioid Agonists", 
    "ENDOCRINE-METABOLIC AGENT",
    "GRANULOCYTE COLONY STIMULATING FACTOR",
    "HEMORRHEOLOGIC AGENT (xanthine)",
    "[EPC],Decreased Central Nervous System Disorganized Electrical Activity [PE],Cytochrome P450 1A2 Inducers [MoA],Cytochrome P450 2B6 Inducers [MoA],Cytochrome P450 2C8 Inducers [MoA],Cytochrome P450 2C19 Inducers [MoA],Cytochrome P450 2D6 Inducers [MoA],Cytochrome P450 3A Inducers [MoA],Cytochrome P450 2C9 Inducers [MoA]",
    "Gastrointestinal",
    "Nutrition",
    "Urinary Alkalinizer",
    "Antihyperthyroid",
    "Electrolyte Supplement, Oral",
    "Antilipemic Agent, HMG-CoA Reductase Inhibitor",
    "Antihypertensive",
    "Neuropathic Pain Agent",
    "Antimalaria",
    "Testosterone replacement therapy", 
    "Antidiarrheal",
    "Miscellaneous ocular agents",
    "ANTIHEMOPHILIC AGENT", 
    "ELECTROLYTE REPLACEMENT THERAPY", 
    "CALCIUM REGULATOR", 
    "ANTICOAGULANT",
    "Neuromuscular Blocking Agent",
    "ANESTHETIC", 
    "RESPIRATORY MEDICINE", 
    "SEROLOGICAL AND IMMUNOASSAY",
    "ELECTROLYE MODIFIERS",
    "IMMUNOSUPPRESSENT",
    "MEDICINES USED IN ENDOCRINE",
    "CORRECTING WATER ELECTROLYTE AND ACID- BASE DISTURBANCES",
    "NASAL MOISTURIZATION", 
    "MUSCULO SKELETAL ",
    "ANTI MALARIAL",
    "ANTI INFECTIVES",
    "OPPORTUNISTIC INFECTION MEDICINES",
    "LOCAL ANESTESIA",
    "THERAPEUTIC FOOD SUPPLEMENT",
    "RESPARATORY MEDICINE",
    "BLOOD PRODUCTS & MEDICINES AFFECTING THE BLOOD",
    "ENDOCRINE DISORDERS MEDICINES",
    "ANTI VIRAL AGENT", 
    "DEFICIENCY DEASES",
    "ANTI NEOPLASTIC AGENT",
    "TREATMENT OF HEADACHE",









]
